=== antony1803/XmlTaskCurses/src/main/resources/data/papers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.kukyan.com/papers"
        xmlns:tns="http://www.kukyan.com/papers"
        elementFormDefault="qualified">

    <element name="papers">
        <complexType>
            <sequence>
                <element ref="tns:press" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="press" type="tns:printedPress" abstract="true"/>
    <element name="magazine" type="tns:magazine" substitutionGroup="tns:press"/>
    <element name="paper" type="tns:paper" substitutionGroup="tns:press"/>
    <element name="booklet" type="tns:booklet" substitutionGroup="tns:press"/>

    <complexType name="printedPress">
        <sequence>
            <element name="title" type="string"/>
            <element name="size" type="integer"/>
            <element name="monthly" type="boolean"/>
            <element name="coloured" type="boolean"/>
        </sequence>
        <attribute name="id" use="required" type="tns:paperId"/>
        <attribute name="printing-country" use="optional" type="tns:country"/>
    </complexType>

    <complexType name="magazine">
        <complexContent>
            <extension base="tns:printedPress">
                <sequence>
                    <element name="subscription-index" type="boolean" default="true"/>
                    <element name="periodicity" type="duration" default="P1M"/>
                    <element name="glossy" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="paper">
        <complexContent>
            <extension base="tns:printedPress">
                <sequence>
                    <element name="subscription-index" type="boolean" default="true"/>
                    <element name="periodicity" type="duration" default="P7D"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="booklet">
        <complexContent>
            <extension base="tns:printedPress">
                <sequence>
                    <element name="glossy" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="pressType">
        <restriction base="string" >
            <enumeration value="magazine"/>
            <enumeration value="paper"/>
            <enumeration value="booklet"/>
        </restriction>
    </simpleType>

    <simpleType name="country">
        <restriction base="string" >
            <enumeration value="Belarus"/>
            <enumeration value="England"/>
            <enumeration value="Poland"/>
            <enumeration value="USA"/>
            <enumeration value="Russia"/>
        </restriction>
    </simpleType>

    <simpleType name="title">
        <restriction base="string">
            <minLength value="2"/>
            <maxLength value="60"/>
        </restriction>
    </simpleType>

    <simpleType name="size">
        <restriction base="integer">
            <minInclusive value="1"/>
            <maxInclusive value="150"/>
        </restriction>
    </simpleType>

    <simpleType name="paperId">
        <restriction base="ID">
            <pattern value="\w{2}-\d{5}"/>
        </restriction>
    </simpleType>

</schema>

=== antony1803/XmlTaskCurses/src/main/resources/data/papers.xml
<?xml version="1.0" encoding="UTF-8"?>
<papers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.kukyan.com/papers"
          xsi:schemaLocation="http://www.kukyan.com/papers ../data/papers.xsd">

    <paper id="ru-10000" printing-country="Russia">
        <title>Вечерняя Москва</title>
        <size>20</size>
        <monthly>true</monthly>
        <coloured>true</coloured>
        <type>paper</type>
        <subscription-index>true</subscription-index>
        <periodicity>P1D</periodicity>
    </paper>

    <paper id="us-10003" printing-country="USA">
        <title>Some American Paper</title>
        <size>12</size>
        <monthly>false</monthly>
        <coloured>false</coloured>
        <type>paper</type>
        <subscription-index>false</subscription-index>
        <periodicity/>
    </paper>    
    
    <booklet id="po-10004" printing-country="Poland">
        <title>Polska volast</title>
        <size>5</size>
        <monthly>true</monthly>
        <coloured>true</coloured>
        <type>booklet</type>
        <glossy>false</glossy>
    </booklet>
    
    <magazine id="en-10002" printing-country="England">
        <title>Times</title>
        <size>50</size>
        <monthly>true</monthly>
        <coloured>true</coloured>
        <type>magazine</type>
        <subscription-index>true</subscription-index>
        <periodicity>P1M</periodicity>
        <glossy>true</glossy>
    </magazine>

    <booklet id="by-10001" printing-country="Belarus">
        <title>Орифлейм предлагает скидки</title>
        <size>1</size>
        <monthly>false</monthly>
        <coloured>true</coloured>
        <type>booklet</type>
        <glossy>true</glossy>
    </booklet>
    
    <paper id="al-10006">
        <title>Аргументы и факты</title>
        <size>20</size>
        <monthly>true</monthly>
        <coloured>false</coloured>
        <type>paper</type>
        <subscription-index>true</subscription-index>
        <periodicity>P7D</periodicity>
    </paper>
</papers>
